apiVersion: apps/v1
kind: Deployment
metadata:
  name: imps-mutating-webhook
  labels:
    app.kubernetes.io/name: imps-mutating-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: imps-mutating-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imps-mutating-webhook
    spec:
      volumes:
        - name: crts
          secret:
            secretName: imps-mutating-webhook-tls
      containers:
        - name: imps-mutating-webhook
          image: imps-mutating-webhook:0.1.0
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /crts
              name: crts
